### ISSUE TITLE
Need more granular error messages

### ISSUE THREAD

**Issue by erickzhao** [scrum-gang/authentication#30]
For example, trying to `/login` with an unconfirmed email right now gives the same message as putting in invalid credentials.
```
{
    "code": "Unauthorized",
    "message": "Authentication failed."
}
```

**Comment by pepoandra** [comment]
i think that in terms of security of your application, you prefer not to give information out about your users and their credentials to unrecognized users, and thats why you dont get any information about what failed, but i guess we could add it since not many hackers will try to steal our users' info

**Comment by erickzhao** [comment]
Yeah, it's fine to not disclose if the account doesn't exist or if the password doesn't exist (and just say "Invalid authentication"), but email confirmations should probably be distinguished.

If someone enters valid credentials but can't log in because they haven't confirmed, then it doesn't have to do with hackers trying to brute force their account because they already have the correct credentials.

Also, it would be good for front-end to know these things so that a confirmation email can be re-sent in case the email went to spam or was deleted by accident.

**Comment by pepoandra** [comment]
Alright, then to resolve the issue we should do something like

Check if user with such credentials exists, if its verified, login. If its not verified & credentials are valid, then return error "Unverified user". IF credentials are not valid, return Authentication failed.

**Comment by erickzhao** [comment]
@pepoandra sounds like a good solution to me!
