### ISSUE TITLE
Test database

### ISSUE THREAD

**Issue by boggy-d** [scrum-gang/authentication#8]
As a backend dev, I want to make sure that I can do CRUD operations on the database. This implies testing for:
- Creating a new entry in the database
- Reading an entry from the database
- Common errors such as no match, null, SQL injection, invalid entries, etc.

(Update and Delete will come in later stories)

**Comment by pepoandra** [comment]
i thought we werent doing issues for testing cause its implied were testing it before pushing =O!

**Comment by Brecchs** [comment]
@pepoandra i split up test and actual implementation in the stories I created to avoid that. That way, we don't need to test before completing the implementation stories, but the testing stories are still there to remind us that we need to do them.

**Comment by boggy-d** [comment]
@pepoandra i split up test and actual implementation in the stories I created to avoid that. That way, we don't need to test before completing the implementation stories, but the testing stories are still there to remind us that we need to do them.
